[package]
name = "lgaircon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.3"
rust-lirc-client-sys = "0.1.0"
rocket = {version = "0.5.0-rc.1", features = ["json"]}
rocket_codegen = "0.4.11"
serde = "1.0.144"
diesel = { version = "2.0.0", features = ["sqlite"] }
diesel_migrations = "2.0.0"
crossbeam-channel = "0.5.6"

[[bin]]
name = "lgaircon"
path = "src/main.rs"
