[package]
name = "lgaircon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lirc-sys = "0.0.1"

[[bin]]
name = "lgaircon"
path = "src/main.rs"
