[package]
name = "lgaircon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-lirc-client-sys = "0.1.0"
diesel = { version = "1.4.8", features = ["sqlite"] }
diesel_migrations = "1.4.0"

[[bin]]
name = "lgaircon"
path = "src/main.rs"
