[build]
xargo = true
build-std = true
default-target = "armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
image = "lgaircon:latest"

[target.armv6-unknown-linux-gnueabihf]
image = "lgaircon:latest"