[build]
xargo = true
build-std = true
default-target = "armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "armv7.Dockerfile"
image = "lgaircon:armv7"

[target.arm-unknown-linux-gnueabihf]
dockerfile = "armv6.Dockerfile"
image = "lgaircon:armv6"
