name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    # container: balenalib/raspberrypi3-debian

    steps:
    - uses: actions/checkout@v3
    
    - name: Update
      run: sudo apt update && apt upgrade
    - name: Install
      run: sudo apt-get install -y liblirc-dev
    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
