name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 
    
    - name: Update
      run: sudo apt update && sudo apt upgrade

    - name: Install
      run: sudo apt-get install -y liblirc-dev libsqlite3-dev curl

    - name: rust-cargo
      uses: actions-rs/cargo@v1.0.1
      with:
        # Cargo command to run (ex. `check` or `build`)
        command: test
        toolchain: nightly

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
