name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 
    
    - name: Update
      run: sudo apt update && sudo apt upgrade

    - name: Install
      run: sudo apt-get install -y podman

    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
    
    - name: Build image
      run: podman build -t lgaircon:latest .

    - name: Cross compile
      run: cross build