name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - arm-unknown-linux-gnueabihf
          - armv7-unknown-linux-gnueabihf
        include:
          - target: arm-unknown-linux-gnueabihf
            docker: armv6.Dockerfile
          - target: armv7-unknown-linux-gnueabihf
            docker: armv7.Dockerfile

    steps:
    - uses: actions/checkout@v3 

    - name: Update
      run: sudo apt-get -y update && sudo apt-get -y upgrade

    - name: Build target image
      run: docker build -f ${{matrix.docker}} -t lgaircon:latest .

    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          target: ${{matrix.target}}
          override: true

    - uses: actions-rs/cargo@v1
      with:
          use-cross: true
          toolchain: nightly
          command: build
          args: --target ${{matrix.target}}
