name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf

    steps:
    - uses: actions/checkout@v3 

    - name: Update
      run: apt-get -y update && apt-get -y upgrade

    - name: Install deps
      run: apt-get -y install podman

    - name: podman build -t lgaircon:latest .

    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          target: ${{matrix.target}}
          override: true

    - uses: actions-rs/cargo@v1
      with:
          use-cross: true
          toolchain: nightly
          command: build
          args: --target ${{matrix.target}}
